# 网站
title: 黄姗
keywords: ['黄姗', '闪闪', '蓬勃人生', '输出实验室']
description: 记录分享令人「健康蓬勃 温暖从容」的工具方法
url: https://sunnyhuang.net
logo: https://ishanshan.zoomquiet.top/share/ishanshan1409-2.png?imageView2/2/w/64

# 社交
social:
  github: https://github.com/ishanshan

# 搜索
algolia:
  appId: X8O4HFU9FV
  apiKey: b72b2cc618f50c44521d1ab1e773f3e7
  indexName: sunnyblog

# 底部
license:
  text: CC BY-NC 4.0 协议
  link: https://creativecommons.org/licenses/by-nc/4.0/deed.zh
copyright: Copyright © 2015-2022 黄姗

# 首页（推荐内容）
highlights:
  - '/cmty/tips_MBOKRframe'
  - '/selfedu/TipsWeekly'
  - '/selfedu/HbOutputWorkFlowy'
  - '/wr/HbOutputbyCards'
  - '/selfedu/RevFacialGrowth'

# 广告位
ad:
#  postBottom: <a target="_blank" href="https://tailwindcss.com/"><img class="w-full mt-10 rounded-md" src="https://tailwindcss.com/_next/static/media/5.cb3efb05f0114abf9efaa0ddbeaed688.jpg"></a>

# 赞赏
sponsor:
  text: 赠酸奶
  tips: 微信扫一扫赞赏作者
  img: https://cdn.chunschen.com/u/1648571434.jpg

# 在 Github 编辑此页
editLink:
  repo: 'ishanshan/ishanshan.github.io'
  text: '在 GitHub 上编辑此页'

# 导航栏
navbar:
  - text: 闪闪人生创造营<sup style="color:orange;">报名中</sup>
    link: /sunnylife/creator-1st
  - text: 关于我
    items:
      - text: 个人简介
        link: /about
      - text: 个人小传
        link: /about/lifestory2203
      - text: 发展规划
        link: /about/plan_lifedev
      - text: 约我时间
        link: /about/booking
      - text: 关爱家人行动清单
        link: /family/TipsCare4Parents

# 侧边栏
sidebar:
  - text: 博客导览
    link: '/blog'
  - text: 像经营企业一样经营人生 | 闪闪人生创造营内测报名
    link: /sunnylife/creator-1st
  - text: 人生蓬勃发展锦囊
    items:
      - text: 理想人生是怎样的，有哪些模式？
        link: '/cmty/model_idealife'
      - text: 通往蓬勃人生，「投入产出比」最高的发力点是什么？
        link: '/cmty/keypoint_flourish'
      - text: 在不确定的时代，如何让人生持续蓬勃发展？
        link: '/cmty/tips_flourishloop'
      - text: 在 VUCA 时代，如何拥有期待的人生？|以终为始·工作坊幻灯分享
        link: https://sunnylife.feishu.cn/wiki/wikcn2UZgndBU40yFOTvxm3qJDh?sheet=FFqkNm
      - text: '「以终为始 敏捷迭代」是怎样一种状态，专家级水平有哪些行为特征？'
        link: https://faciloutput.feishu.cn/sheets/shtcnCjUbsgCpYkWMWKxWMNTuNh?sheet=f08271
      - text: 希望人生更从容且有方向？试试这个小本子 ·「人生彩虹本」使用手记
        link: '/selfedu/tips_rainbowbook'
      - text: 这座线上心理健身房，你，值得拥有
        link: '/selfedu/ebp_happiness'
      - text: 如何梳理有助于达成长期目标的行动规划？
        link: '/cmty/tips_MBO_fromend'
      - text: OKR是一套严密的思考框架？这是啥意思？
        link: '/cmty/tips_MBOKRframe'
      - text: 如何从容应对新挑战？·研究最佳实践的通用问题清单&常见陷阱
        link: '/cmty/tips_RES_BP'
      - text: 启动新项目，如何设定项目目标? · 项目需求采集问题清单
        link: '/cmty/infoq_pm_pre'
      - text: 如何提升行动意愿？· 行动清单汇总
        link: '/cmty/tips_motivation'
      - text: 如何更易获得有效帮助？· 困扰分析模板
        link: '/cmty/hb_ask4help'
      - text: 如何给自己找 mentor 加速成长？关键有四步
        link: '/cmty/hb_getmentors'
      - text: 职业发展
        items:
          - text: 如何做职业选择？· STC 问题清单
            link: '/cmty/tips_career_choice'
          - text: 用心写周报的同事，绩效不会太差
            link: '/selfedu/TipsWeekly'
          - text: 希望团队配合更紧密、成长更迅猛？试试这样1on1
            link: '/cmty/tips_1on1'
  - text: 人生探索实践
    items:
      - text: 探索付费产品服务切入点
        items:
          - text: 转折期与师友相伴，持续创造人生新可能|闪闪同行计划 内测报名
            link: '/flourish/gotogether-1st'
          - text: 在复杂多变的时代，如何更早拥有自己期待的人生？ |「人生·敏捷迭代营」内测招募
            link: '/flourish/f_grow'
          - text: 尝试产品商业化这俩月的进展分享 & 「人生·敏捷迭代营」内测招募
            link: '/f_output/f_test_3rd'
          - text: 职业转型路茫茫，怎么办？来士别三日行动营，一起「拥抱不确定」
            link: '/f_output/f_test_2nd'
          - text: 想让职业转型的「试错节奏」快起来？「士别三日行动营」了解一下
            link: '/f_output/f_test_1st'
          - text: 对输出实验室的七大误解，你中了几个？
            link: '/f_output/misunderstanding'
          - text: 主持人指南
            link: '/f_output/hb_facilitator'
      - text: 开发手记
        items:
          - text: 如果在「人生·敏捷迭代营」小组练习时，作为案主感觉收获不大，是什么情况？
            link: '/mur/fo_practicemore'
          - text: 开始把「获得顶级心流体验」的心法，融入小组练习·迎来又一个小里程碑_220218
            link: '/f_output/mst_unitedby_agoal'
          - text: 有测量才易有进步 · 初次尝试信任增进小练习有感_211010
            link: '/mur/fo_creditws1st'
          - text: U MADE MY DAY！· 有感于输出实验室又一里程碑
            link: '/f_output/mst_got2partners'
          - text: 愈发感觉输出实验室的玩法，太爽了
            link: '/mur/happiness_f_o_organizer'
          - text: 向世界交付自己的价值 · 有感于输出实验室又一里程碑
            link: '/mur/happiness_devpdt_host'
      - text: 各方交流反馈
        items:
          - text: 用户反馈/往期成员结营复盘
            link: '/f_output/feedback'
          - text: 关于输出实验室玩法的讨论@xk_210729
            link: '/f_output/feedback_xk'
          - text: 自组织实践：如想助力彼此实现目标，怎么办？@东东_210928
            link: '/f_output/fb_dd_revOKRtog'
          - text: 自组织实践：如对输出实验室有期待，怎么办？@章鱼狗_210704
            link: '/f_output/fb_od_hopeselforg'
          - text: 身边都是正反馈，会不会让你误以为输出实验室是可以服务大部分人的？@六一_210804
            link: '/f_output/fb_61_remindbias'
          - text: 为什么不单独打磨定OKR或做复盘的产品/工具包？@立人 210716
            link: '/f_output/fb_lr_devseparate'
      - text: 归档
        items:
          - text: 输出实验室 玩法介绍
            link: '/f_output'
          - text: 输出实验室 需要哪些支持？
            link: '/f_output/helpwanted'
          - text: 报名入口
            link: '/f_output/signup'
          - text: 常见疑问解答/FAQ
            link: '/f_output/faq'
          - text: 如何用好这里的资源/各角色进阶攻略
            link: https://faciloutput.feishu.cn/sheets/shtcnS82zs4mEKUzTTMuUddnCdg?sheet=nGAbzW
  - text: 早期主题实践手记
    items:
      - text: 写作
        collapsed: true
        items:
          - text: 工具方法
            items:
              - text: 卡片助力输入输出，工具我选 WorkFlowy
                link: '/selfedu/HbOutputWorkFlowy'
              - text: 卡片助力输出， MarkDown + GitHub + LOFTER 有轻功
                link: '/wr/HbOutputbyCards'
              - text: 这样用七牛，插图优雅又省心 · MarkDown 码字发文最佳实践
                link: '/wr/HbMarkdownImage'
              - text: 命名用英文，烦恼少大半 · 团队文档命名指南
                link: '/cmty/HbDocName'
              - text: 实用但小众的 MarkDown 技巧
                link: '/wr/HbMarkdownTrick'
              - text: 给文字工作者的 GitHub 上手攻略
                link: '/wr/HbGitHubPre'
          - text: 日常练习
            items:
              - text: 跟王烁「老婆推」学记趣和爱 · 杂记
                link: '/wr/TipsFascinatingLife'
              - text: 你丁酉年的故事
                link: '/selfedu/Review2017'
              - text: 谢谢你给她的时光
                link: '/selfedu/Letter2XY4y2017'
          - text: 笑来写作训练营手记
            items:
              - text: 训练营介绍
                link: '/wr/course_xl/intro'
              - text: ch1 文字的本质 · 圈词练习
                link: '/wr/course_xl/ch1'
              - text: ch2 一切创作的前提都是选择 · 教程创作练习
                link: '/wr/course_xl/ch2'
              - text: ch3 格式化创作 · 2W1H分析练习
                link: '/wr/course_xl/ch3'
              - text: ch4 逻辑模板 · 并列、递进、转折拆解练习
                link: '/wr/course_xl/ch4'
              - text: ch5 修辞正义 · 《围城》类比赏析
                link: '/wr/course_xl/ch5'
              - text: ch6 输入为本 · 输入练习
                link: '/wr/course_xl/ch6'
              - text: ch7 超级专业 · 梳理练习规划
                link: '/wr/course_xl/ch7'
              - text: 好奇带来奇妙旅程 · 结业手记
                link: '/wr/review_course_xl'
      - text: 面部健康生长
        items:
          - text: 我如何成为换头最快的1%？· 过去8个月的面容调整复盘
            link: '/selfedu/RevFacialGrowth'
          - text: 学习资源
            link: '/family/ResFacialGrowth'
          - text: 常见疑问&练习锦囊
            link: '/family/TipsFacialGrowth'
      - text: 产品策划开发
        items:
          - text: 最佳实践观察手记
            link: '/devpdt'
            items:
              - text: 教育领域
                items:
                  - text: 线上课程如何给用户良好的同侪环境
                    link: '/devpdt/BP_peer_envir'
                  - text: 怎样设置练习任务更易达到教学目标
                    link: '/devpdt/BP_asgmt_des'
                  - text: 借 AI 促进教学的案例
                    link: '/devpdt/BP_AIedu'
                  - text: 三节课教学模式亮点
                    link: '/devpdt/InfoLearning3jk'
              - text: 通用
                items:
                  - text: 优雅的信息架构
                    link: '/devpdt/BP_IA'
                  - text: Elegant Coding Style
                    link: '/devpdt/HbCodingStyle'
                  - text: 策略产品经理工作锦囊
                    link: '/devpdt/Tips4StratPM'
                  - text: 如何做竞品调研
                    link: '/devpdt/HbCI'
          - text: 杂记
            items:
              - text: 学习资源分享
                link: '/devpdt/IdxLearningRes'
              - text: '✪为什么「美团买菜」如此重视用户反馈并快速迭代改进？'
                link: '/devpdt/mur_strat_mtfood'
              - text: 这波内容付费平台困境出路会在哪?
                link: '/devpdt/TipsEduPdtCHAL'
              - text: K12 头部产品如何高效增加复购？
                link: '/devpdt/TipsEduK12Effect'
              - text: 先做大功能模块，还是优化型需求？
                link: '/devpdt/mur_DevPriority'
          - text: 策略产品经理训练营手记
            items:
              - text: 手记简介
                link: '/devpdt/3jkSPM/intro'
              - text: 学习计划&执行情况
                link: '/devpdt/3jkSPM/PlanStudy'
              - text: Chap1 了解策略和策略产品
                link: '/devpdt/3jkSPM/ch1'
              - text: Chap1 Task 分析两个功能中的策略四要素
                link: '/devpdt/3jkSPM/ch1Task'
              - text: Chap1 学习过程复盘
                link: '/devpdt/3jkSPM/ch1Review'
              - text: Chap2 策略产品发现问题的四个方法
                link: '/devpdt/3jkSPM/ch2'
              - text: Chap2 Task 优化豆瓣图书推荐效果
                link: '/devpdt/3jkSPM/ch2Task'
              - text: Chap2 学习过程复盘
                link: '/devpdt/3jkSPM/ch2Review'
              - text: Chap3 策略产品工作的通用方法论
                link: '/devpdt/3jkSPM/ch3'
              - text: Chap3 Task 优化小红书支付体验
                link: '/devpdt/3jkSPM/ch3Task'
              - text: Chap3 学习过程复盘
                link: '/devpdt/3jkSPM/ch3Review'
              - text: Chap4 策略在核心业务上的应用
                link: '/devpdt/3jkSPM/ch4'
              - text: Chap4 Task 优化微博搜索体验
                link: '/devpdt/3jkSPM/ch4Task'
              - text: Chap4 学习过程复盘
                link: '/devpdt/3jkSPM/ch4Review'
              - text: Chap5 策略在其他业务上的应用
                link: '/devpdt/3jkSPM/ch5'
              - text: Chap5 Task 设计网易蜗牛读书增长方案
                link: '/devpdt/3jkSPM/ch5Task'
              - text: Chap5 学习过程复盘
                link: '/devpdt/3jkSPM/ch5Review'
              - text: Chap6 Task 优化天气 query 识别策略
                link: '/devpdt/3jkSPM/ch6Task'
              - text: Chap6 学习过程复盘
                link: '/devpdt/3jkSPM/ch6Review'
              - text: Final 毕业设计
                link: '/devpdt/3jkSPM/ch6'
      - text: 摇摆舞（Swing）
        items:
          - text: Swing 吧！你的苦乐，swing 知道
            link: '/selfedu/YouNeedSwing'
          - text: 摇摆舞（Swing）手记导览
            link: '/swing'
          - text: Swing 新人指南
            link: '/swing/HbBeginner'
          - text: Swing 舞会指南
            link: '/swing/HbParty'
          - text: Swing 动作心得
            link: '/swing/TipsMovement'
          - text: Swing 星标资源
            link: '/swing/ResHighLight'
  - text: 关于我
    items:
      - text: 简介
        link: '/about'
      - text: 个人小传
        link: '/about/lifestory2203'
      - text: 发展规划
        link: '/about/plan_lifedev'
      - text: 理想生活
        link: '/about/idealife'
      - text: 约我时间
        link: '/about/booking'
      - text: 招亲帖：这位男同学，如果你也想找个偏好创造型快乐的靠谱伴侣…
        link: '/family/lifep_Ad'
      - text: 答招亲帖「相识十五问」@Sunny
        link: '/family/lifep_QAishanshan'
      - text: 我是怎样的人？那些认识三年以上的老友，给出的答案是…
        link: '/about/view_others'
      - text: 探寻人生伴侣的路线图
        link: '/family/lifep_roadmap'
      - text: 关爱家人行动清单
        link: '/family/TipsCare4Parents'
      - text: 投资决策框架：如何评估一项资产是否值得长期持有？
        link: '/selfedu/tips_invest'
      - text: 养娃清单
        link: '/family/hb_parenting'
      - text: 自我教育
        items:
          - text: 如何减少消极情绪？我的4项应急预案和5项防范措施
            link: '/cmty/tips_happiness'
          - text: 如何给自己找 mentor 加速成长？关键有四步
            link: '/cmty/hb_getmentors'
          - text: 如何更易获得有效帮助？· 困扰分析模板
            link: '/cmty/hb_ask4help'
          - text: 如何提升行动意愿？· 行动清单汇总
            link: '/cmty/tips_motivation'
          - text: 近三年来，我发生的主要变化有哪些？
            link: '/selfedu/rev_3years'
          - text: 希望团队配合更紧密、成长更迅猛？试试这样1on1
            link: '/cmty/tips_1on1'
          - text: 好奇带来奇妙旅程 · 笑来写作训练营结业手记
            link: '/wr/review_course_xl'
          - text: 希望人生更从容且有方向？试试这个小本子 ·「人生彩虹本」使用手记
            link: '/selfedu/tips_rainbowbook'
          - text: 从迷茫焦虑到从容踏实，这两个月我干了啥？· 万字复盘
            link: '/selfedu/review2021Q1'
          - text: 这座线上心理健身房，你，值得拥有
            link: '/selfedu/ebp_happiness'
          - text: 幸福再体验：我生活中最美好的经历
            link: '/selfedu/savor_happiestevent'
          - text: 我如何成为换头最快的1%？· 过去8个月的面容调整复盘
            link: '/selfedu/RevFacialGrowth'
          - text: 如何提升企业绩效？研究杨国安思想体系后，我发觉的四大常见误区
            link: '/cmty/tipsOD'
          - text: 如何带出和自己一样能干的团队 · 半年摸爬小记
            link: '/selfedu/TipsTeamLead101'
          - text: 你丁酉年的故事
            link: '/selfedu/Review2017'
          - text: 谢谢你给她的时光
            link: '/selfedu/Letter2XY4y2017'
          - text: 卡片助力输入输出，工具我选 WorkFlowy
            link: '/selfedu/HbOutputWorkFlowy'
          - text: 用心写周报的同事，绩效不会太差
            link: '/selfedu/TipsWeekly'
          - text: 想让生活不再满是工作？试试远距联想
            link: '/selfedu/TipsWorkHappier'
          - text: 和大 Boss 协同，你有什么秘诀？邮件先行。
            link: '/selfedu/TipsBossCooperate'
          - text: 我挺好，别担心 · 写在工作一周年边上
            link: '/selfedu/WorkFor1Year'
          - text: 改变我玩耍习惯的 10 场活动
            link: '/selfedu/IdxActivity'
          - text: 讲座控，控住你的人生 · 学习自传（一）
            link: '/selfedu/SelfEduOwetoJZK'
          - text: 入职第一天，我失眠了
            link: '/selfedu/NewLifeinOMC'
      - text: 杂记/mur
        items:
          - text: 答师友：第一次换工作就涨薪200+%，我是如何实现的？
            link: '/mur/tips_jobhunting'
          - text: 答师友：我的个人发展规划是怎么梳理出来的？
            link: '/cmty/tips_MBOlifeplan'
          - text: 向世界交付自己的价值 · 有感于输出实验室又一里程碑
            link: '/mur/happiness_devpdt_host'
          - text: 答师友：升级个人博客背后的思考
            link: '/mur/logOD_TRIZblogupd'
          - text: 如何高效解决难题 ·《创新算法》学习有感&资源索引
            link: '/mur/res_ARIZ'
          - text: 进展两则：博客将要升级，「输出实验室」周日早10点截止报名
            link: '/mur/upd2105'
          - text: 博客在升级 · 主页提示
            link: '/mur/welcome_blogupding'
          - text: 不要评判某事好坏 · 杂记
            link: '/mur/depend_on_your_goal'
          - text: 由“拥抱变化”引发的羞愧和反思 · 杂记
            link: '/mur/TipsEmbraceChange'
          - text: 对新发展机会的期待 · 杂记
            link: '/about/InfoVocationREQ'
          - text: 如果你也在天上挑妈妈 · 家书 000
            link: '/mur/LetterFamily000Baby'
          - text: 体能 不能落 · 杂记
            link: '/mur/TipsMorningExercise'
          - text: 活动主持人如何快速进入状态？如何从源头避免编程初级错误？· 170311 见 @ZoomQuiet 小记
            link: '/mur/LogMeetup170311ZqBJ'
