name: Check Link (Scheduled)

on:
  schedule:
    - cron: "0 6 * * 0"

jobs:
  check-markdown-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'no'
          config-file: .github/workflows/markdown-link-check.json
          base-branch: ${{ github.base_ref }}
