name: Check Link (PR)

on:
  pull_request:
    branches: [ master ]

jobs:
  check-markdown-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: .github/workflows/markdown-link-check.json
          base-branch: ${{ github.base_ref }}
